### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by AlexThePotter** [MorneSaunders360/Solar-Sunsynk#12]
It was working just fine, but last 19 hours it's done nothing. 

Sunsynk platform is accessible, is there a way I can refresh the integration or has something changed?

**Comment by MorneSaunders360** [comment]
Hi AlexThePotter

You can try to reload the integration, see screenshot below or restart home assitant to clear cache and reload the integration.
![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/de3ea629-bc90-48d8-96fb-fcabd0762a07)
I have picked up that sunsynk seems to be making changes on their side as my sunsynk solar system is also not updating on the sunsynk platform and shows as offline even though it is connected to the wifi and the dongle connected to the inverter shows as connected to wifi and the sunsynk cloud platform.

You can also verify by disabling the sunsynk intergration on home assistant and then check the sunsynk platform if your solar system is updating its values.

It seems like sunsynk is making changes on their side as there is now a few new reqions, might be that they are expanding and this might cause the solar system to not update in the solar sunsynk integration in home assistant.
![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/9ca65b43-c189-4d1c-abcd-53d81dcb0f86)
