### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by ElectricMolehill** [MorneSaunders360/Solar-Sunsynk#14]
Thanks for your API documentation it's proving invaluable for a solar optimization project I'm involved in. In return, can I offer something I've gleaned from elsewhere - I believe json key for 'Use Timer' is {"peakAndVallery": "1"} (including spelling mistake!)
Also, according to my testing for Work Mode:
0 = Selling first (= Zero Export off, Solar Export off, Limit to Load only off) 
1 = Zero Export + Limit to Load Only (= Zero Export on, Solar Export on, Limit to Load only on)
2 = Limited to Home (= Zero Export on, Solar Export on, Limit to Load only off)

cheers
Mark

**Comment by MorneSaunders360** [comment]
Thanks mark, will update the API documentation.
