### ISSUE TITLE
error adding repository

### ISSUE THREAD

**Issue by SHadley1138** [MorneSaunders360/Solar-Sunsynk#17]
every time I try to add the repository, I get this error "Repository MorneSaunders360/Solar-Sunsynk not found". very odd

**Comment by MorneSaunders360** [comment]
Hi hi

That is really odd. Please ensure you have the latest hacs and Home assistant installed.

We have also added a button in our repo to add the repo to home assistant.

![Screenshot_20240709_191404_GitHub.jpg](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/226bcb8b-163c-4dd3-96df-1b23fd467643)

It might also be that there is a bug in hacs or home assistant when adding the repo, does this also happen when you add another repo to hacs?

**Comment by SHadley1138** [comment]
Attachment available until 8 Aug 2024
Im not sure what im doing wrong, I dont use HACS that often, but the few I have work ok

I made a couple of videos to show you what’s happening

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAdfbOVbG4vL5kzQlEQVTj-RA-DT3Aa0U1G63gMbuYdlwzUHrHOt8icMx%2F%24%7Bf%7D%3Fo%3DAgSWz_U2uP0EVQD0pKuqhauYkxXj0mT6saHrYfnLhG8Z%26v%3D1%26x%3D3%26a%3DCAogl7LnNNGaUR0tt9lizt0hTsLKJsMxwvD-E1KsxkkjPsMSdhCOm5DGiTIYjquLmpMyIgEAKgkC6AMA_0xKvL5SBED4NPdaBHyJwzFqJSAUHHXCwMhgvIsJGbk5r1W8FmGmsyG2XZ1wn7GZnyYu7Ld7L_dyJf5ihiEjUHJJSCHe3TpLD8-JkMgcotUTsLAltnhcjexSFGu39eM%26e%3D1723141903%26fl%3D%26r%3D19D6E424-0E7E-4A90-8DA7-786C73609532-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DF2CAEFA7-A421-4FBF-9F26-6A467057916E%26p%3D58%26s%3D4iv2Su1DZRkmHyhs1czGog8BEVo&uk=8iBhc4JomgR0QvD35CdltQ&f=Screen%20Recording%202024-07-09%20at%2019.26.49.mov&sz=23980718>Screen Recording 2024-07-09 at 19.26.49.mov
24 MB

**Comment by SHadley1138** [comment]
apologies for the url video post

**Comment by MorneSaunders360** [comment]
Cool, thanks for the video, I remove my repo from HACS and used the button on this repo and I'm also able to replicate the issue. 
I will investigate and report back on a fix asap.

**Comment by MorneSaunders360** [comment]
Okay, I have found the issue with the button and made a patch for it, you can try the add button on this repo again.
Let me know if this patch works for you?

**Comment by SHadley1138** [comment]
Sadly not….  Using the button, it connects to my HA, then I get this error
Repository MorneSaunders360/Solar-Sunsynk not found

**Comment by MorneSaunders360** [comment]
Hmm.. Okay, let's try to do it manually.
Go to hacs and head into the integrations section.

The click on the hamburger menu icon(the three dots) and select custom repository.
![Screenshot_20240709_234130_Home Assistant.jpg](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/cef34cfd-a3b7-40cb-b464-93d03e526b3f).

Then add the repo using this url
https://github.com/MorneSaunders360/Solar-Sunsynk

Select the integration option and then click on the add button.
![Screenshot_20240709_234401_Home Assistant.jpg](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/2e47bbf9-e0f4-4be0-a82c-b03a24efcecb)

Then it should appear on the list.
![Screenshot_20240709_234420_Home Assistant.jpg](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/f359ebbc-c94a-4d1c-bfdc-529e463e9b96)

![Screenshot_20240709_234445_Home Assistant.jpg](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/cae6a8e6-4da3-481a-b5a1-7f0870f9a83e)

**Comment by SHadley1138** [comment]
Hi,
Ive given it a go manually, but I get this error...


￼

**Comment by MorneSaunders360** [comment]
This is a weird one. Hmm, do you know what version of hacs you are currently using?

**Comment by SHadley1138** [comment]
It reckons 1.34.0On 11 Jul 2024, at 09:31, Morne ***@***.***> wrote:﻿
This is a weird one. Hmm, do you know what version of hacs you are currently using?

**Comment by MorneSaunders360** [comment]
Hmm, okay, so my version is the same. Maybe the home assistant is outdated?

**Comment by SHadley1138** [comment]
No, I’m running 14.7.2On 12 Jul 2024, at 14:43, Morne ***@***.***> wrote:﻿
Hmm, okay, so my version is the same. Maybe the home assistant is outdated?

**Comment by MorneSaunders360** [comment]
Okay lets then check the HA Core version this is my current version
![image](https://github.com/user-attachments/assets/95aac2d9-e64a-4333-98df-9fc39f806841)
