### ISSUE TITLE
Solar-SunSynk 1.0.11 API issues 

### ISSUE THREAD

**Issue by wtsz1** [MorneSaunders360/Solar-Sunsynk#19]
I have been looking for something like this for a while, gave up then started looking again and come across across the Solar-SunSynk. I have a SunSynk 3.6 inverter with batteries (with an AC cupping not DC). SunSynk are unable to support overcharging the batteries in this setup. So this integration is perfect for HA and keen to use the work mode feature. 

I have an issue where my changes are not being accepted. A PCAP shows two way communication, but an empty payload and a reset from SunSynk. I have tested this a number of different ways on HA but primarily using Actions in the development tool and the logs only highlight a certificate warning when actioning. I have downgraded having tried two other versions which error straight away, which I guess is because of the region change (line 36). I have read the closed issues but unable to grasp how everyone is testing with JSON through HA. 

I have followed all the guides however unable to write back to the cloud.

Please can you help me, the integration looks great. 

Thanks

**Comment by MorneSaunders360** [comment]
Hi wtsz1,

Apologies for the delayed response. It seems that the GitHub issues ended up in the spam folder. I'll investigate the issue where you're unable to write back to the cloud and respond as soon as possible.

If you're wondering how we're able to communicate with the Sunsynk API using JSON, we use the Postman tool to send the JSON and then check the response payload. For example, to address your issue, we make a call like this and then review the payload:

```bash
curl --location 'https://api.sunsynk.net/api/v1/common/setting/2107269334/set' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
    "sn": "2107269334",
    "safetyType": "2",
    "battMode": "-1",
    "solarSell": "0",
    "pvMaxLimit": "8000",
    "energyMode": "0",
    "peakAndVallery": "1",
    "sysWorkMode": "2",
    "sellTime1": "01:00",
    "sellTime2": "05:00",
    "sellTime3": "12:30",
    "sellTime4": "13:00",
    "sellTime5": "17:00",
    "sellTime6": "21:00",
    "sellTime1Pac": "8000",
    "sellTime2Pac": "8000",
    "sellTime3Pac": "8000",
    "sellTime4Pac": "8000",
    "sellTime5Pac": "8000",
    "sellTime6Pac": "8000",
    "cap1": "70",
    "cap2": "70",
    "cap3": "70",
    "cap4": "70",
    "cap5": "70",
    "cap6": "70",
    "sellTime1Volt": "49",
    "sellTime2Volt": "49",
    "sellTime3Volt": "49",
    "sellTime4Volt": "49",
    "sellTime5Volt": "49",
    "sellTime6Volt": "49",
    "zeroExportPower": "0",
    "solarMaxSellPower": "9000",
    "mondayOn": true,
    "tuesdayOn": true,
    "wednesdayOn": true,
    "thursdayOn": true,
    "fridayOn": true,
    "saturdayOn": true,
    "sundayOn": true,
    "time1on": false,
    "time2on": false,
    "time3on": false,
    "time4on": false,
    "time5on": false,
    "time6on": false,
    "genTime1on": false,
    "genTime2on": false,
    "genTime3on": false,
    "genTime4on": false,
    "genTime5on": false,
    "genTime6on": false
}'

**Comment by wtsz1** [comment]
hiya, 

Not to worry I had a power cut 3 times so it destroyed my VM :). I was hoping to reply sooner. Needed tp rebuild HA. Interestingly, I get this error.

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/291afbc0-4d82-497c-8411-9ed8f85cecd7">

Any help on the errors and code would be highly appreciated.

Thank you

**Comment by wtsz1** [comment]
Also, thank you for the JSON. I have this working in postman now. 

PostMan
<img width="739" alt="image" src="https://github.com/user-attachments/assets/90a1a89c-848d-4efb-9b74-14101f6c55a7">

SunSynk
<img width="855" alt="image" src="https://github.com/user-attachments/assets/85cc7cd8-2b8e-453b-bf4b-438bc93664fb">

**Comment by MorneSaunders360** [comment]
> hiya,
> 
> Not to worry I had a power cut 3 times so it destroyed my VM :). I was hoping to reply sooner. Needed tp rebuild HA. Interestingly, I get this error.
> 
> <img alt="image" width="1347" src="https://private-user-images.githubusercontent.com/40600856/375985148-291afbc0-4d82-497c-8411-9ed8f85cecd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTYyODgsIm5iZiI6MTcyODgxNTk4OCwicGF0aCI6Ii80MDYwMDg1Ni8zNzU5ODUxNDgtMjkxYWZiYzAtNGQ4Mi00OTdjLTg0MTEtOWVkOGY4NWNlY2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEwMzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNzg0ZDUyZDJkOTZiNGVkNDg1YjQxZTk1NTEwOWYzYjY0N2FkNmZkMGYwZDg5MDBlY2I3ZDA3YWZlYWY4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KSCXnLteGfjx6TqB4tqwhW7Vk51xvfBCMnCZObFnxqk">
> Any help on the errors and code would be highly appreciated.
> 
> Thank you


This happens when you use Home Assistant over HTTP instead of HTTPS, leading to the following error. This might also be the reason why you were unable to set your Sunsynk battery settings. Maybe try to use a proxy and make your Home Assistant secure

**Comment by wtsz1** [comment]
I would agree however, curl is working both directly on my laptop and the HA terminal. The request to SunSynk would only become SSL/TLS if it was a requirement for communication and, all my successful testing has not been completed using TLDR. From my understanding. 

It would require SunSynk to share certificates with customers to formula that level of trust. HA is displaying a warning, I have enabled SSL and can confirm the warning is still displayed. 

Thank you for your help so far.

**Comment by MorneSaunders360** [comment]
You are most welcome!

When you are using actions in home assistant, do you get a green response back when clicking the button.
Try to run this in home assistant, an let me know if your Sunsynk inverter is updating, if it is updating then we just need to figure out what settings we need to put together to make the "Work  mode" actually apply in the cloud else there is a bug that needs fixing

![image](https://github.com/user-attachments/assets/db459ae7-0992-45d7-948a-66c2824a6f48)

**Comment by wtsz1** [comment]
I can confirm I do receive the green tick

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/0ddedce7-0c94-457f-95e8-2f3ab7449b54">


The inverter did not update. 

Thank you

**Comment by wtsz1** [comment]
I noticed that a few " where missing and an error in the YAML. 
![image](https://github.com/user-attachments/assets/c4043a99-30b9-4746-bcf7-c0e07dbaa263)

Fantastic, thank you for sharing. Looking forward to the automation :)

**Comment by MorneSaunders360** [comment]
When you run this in postman do you get any error?

```bash
curl --location 'https://api.sunsynk.net/api/v1/common/setting/2107269334/set' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer YourToken' \
--data '{
    "sn": "2107269334",
    "cap1": "70",
    "cap2": "70",
    "cap3": "70",
    "cap4": "70",
    "cap5": "70",
    "cap6": "70"

}'

**Comment by wtsz1** [comment]
Hi the integration is working thank you. The YAML screenshot was different to mine in HA.
cheers
