### ISSUE TITLE
Missing sensors

### ISSUE THREAD

**Issue by Nurgus** [MorneSaunders360/Solar-Sunsynk#5]
I was using the sensors _loadOrEpsPower and _gridormeterpower for house load and grid load respectively. Having updated today, all the sensors are renamed and I can't find these two values. 

None of the numbers for any entities seem to match.

![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/17724232/673c1ccb-cbe0-4241-985c-68ad86a87e27)

**Comment by Nurgus** [comment]
I'm guessing that _instantaneous_grid_i_o and _instantaneous_load are  the sensors I need but they're a wildly different.


![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/17724232/139f0872-fcab-46c9-a263-79c7b944cd50)
![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/17724232/3d71663b-d85e-4ba9-b6d2-5b77b3d8e315)

**Comment by MorneSaunders360** [comment]
Hi Nurgus,

I wanted to address a few points concerning the current Sunsynk API's integration with Home Assistant. I have identified several issues that I believe may be leading to the instability you've been experiencing. 

Firstly, I found that the initial setup of the device as a service was incorrect, which may be contributing to the hanging/crashing problem with Home Assistant. 

Secondly, it appears that some extraneous sensors were inadvertently included in the device display, which don't pertain to the Sunsynk integration. This is an area that certainly needs rectifying to avoid potential confusion and system overload.

Additionally, I realized that the integration needs to accommodate multiple solar systems, as a plant could potentially contain more than one inverter. 

I also forgot to change the refresh timer, current it was 30 second, I will change it back to 10 second. 
I also change the name to be sunsynk_{plantId}_{inverterId}

Furthermore, I am currently enhancing the Sunsynk integration to function effectively with the Energy Dashboard. I understand that this feature was not working as expected before, which may have caused some inconvenience.

I deeply appreciate your patience as I work on resolving these issues. Please feel free to share any additional feedback you might have. Your insights are invaluable in helping me improve this integration. I will keep you updated as progress is made and aim to rectify the situation as promptly as possible.

**Comment by MorneSaunders360** [comment]
We also get the data now straight on inverter level
 
instantaneous_load = loadOrEpsPower
_instantaneous_grid_i_o = gridOrMeterPower

Let me know if I'm wrong, I'm still trying to figure out where to map each sensor correctly

**Comment by MorneSaunders360** [comment]
Update

Instantaneous Grid I/O Total = gridOrMeterPower
Instantaneous Load = loadOrEpsPower

I hope this helps, please let me know if have any other problems

**Comment by Nurgus** [comment]
Hi, I'm impressed with how this integration is coming along and excited to get started using the service to control my Sunsynk gear!

> Instantaneous Grid I/O Total = gridOrMeterPower
> Instantaneous Load = loadOrEpsPower

The problem I have is that these sensors are giving me totally different readings to the ones I get from the sunsynk app.

In the screenshot, my house is pulling 7923w yet the Instantaneous Load sensor says 292w

From the grid it's pulling 26w and the Instantaneous Grid I/O Total sensor shows -1945w, These sensors are always wrong.

Instantaneous Battery and Instantaneous Generation sensors are always correct.

Let me know if I can provide any more information.

**Comment by MorneSaunders360** [comment]
So I think what might have happened was the refresh timer for the integration was set 30 seconds and that might be the reason for why the data is not matching in your app and in home assistant. I have updated the timer back to 10 seconds.
I will take a look at the Instantaneous Grid I/O Total as it might read the wrong sensor values will keep you updated.
This is how my data looks like:
![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/343a1492-fc8d-4731-90ed-31db6e3bb5fe)

**Comment by Nurgus** [comment]
I've been refreshing the app and comparing the numbers to this integration almost continuously since yesterday and there's been no moment where those two sensors have been anywhere near to matching up. Meanwhile the generation and battery sensors are spot on.

Something's definitely not right but I don't know how to diagnose it further.

**Comment by MorneSaunders360** [comment]
So what I have experienced with home assistant and HACS is that we you update the integration, it does not always download the update files. What we can do is go to HACS > Integrations > Solar Sunsynk > Go into the Integration and Click on re-download the integration.
![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/f063ab9b-ee5c-4cb8-aa08-afd8070aabe8)
Let me know if this helps, other then that, I can give you the old branch with the old integration code (This will be the last resort if all fails)?

**Comment by Nurgus** [comment]
![Screenshot_20230630_110329_Sunsynk Connect](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/17724232/1244b473-e3fa-4cdd-941e-a1d80d058b46)
![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/17724232/2d4438c2-16c0-49e1-928d-931585a7931f)

EDIT: Sorry, wrong screenshot, fixed.

This illustrates the problem. In Sunsynk connect the load is around 450w and then jumps to around 1500w with not much in between. In Home Assistant the load history is very spiky and doesn't match up at all.

**Comment by Nurgus** [comment]
> Integrations > Solar Sunsynk > Go into the Integration and Click on re-download the integration.

Done, no improvement.

> other then that, I can give you the old branch with the old integration code (This will be the last resort if all fails)?

Nah I want to help crack the problem. Let me know if you think of anything to test or any information I can provide.

**Comment by MorneSaunders360** [comment]
Hmmm.... okay I'm going to use sunsynk virtual user and then I will check their system and see if I can see anything out of the ordinary.

**Comment by MorneSaunders360** [comment]
I can see the differences now
![image](https://github.com/MorneSaunders360/Solar-Sunsynk/assets/60499349/6d65d460-c545-4b8f-bc18-127f556b2e1d)

**Comment by MorneSaunders360** [comment]
Okay, updated the integration, check if your sensors is now updating the correct values.

**Comment by Nurgus** [comment]
Oh yes wow, that's fixed it. All sensors looking good.  What was the problem?

**Comment by MorneSaunders360** [comment]
Awesome glad it works,So it seems like there is more than one place you can get the sensor values for grid and load. The ones I selected were the individual values that needed calculation and the correct ones are already calculated
