### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by a-c-m** [MorneSaunders360/Solar-Sunsynk#6]
Thanks for creating this. 

I also found https://github.com/slipx06/sunsynk-power-flow-card which gives a nice UI to the data. I've not managed to line up all the numbers properly yet - but thought you might like to see it.

**Comment by MorneSaunders360** [comment]
Hi there,

Thank you for sharing the resource! The sunsynk-power-flow-card project on GitHub looks really interesting. It seems like a great way to visualize the data in a more user-friendly and understandable format.

I appreciate you pointing me towards this project and I'm definitely keen on exploring it further. Let me know if there's anything else you come across that you think would be of interest.
